# Generated by Django 2.2.7 on 2019-11-29 12:22

from django.db import migrations, models
import django.db.models.deletion
import travelportal_api.apps.TravelPortalSearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelPortalSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('code', models.CharField(max_length=3, validators=[travelportal_api.apps.TravelPortalSearch.models.validate_airport_code])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('code', models.CharField(max_length=3, validators=[travelportal_api.apps.TravelPortalSearch.models.validate_airport_code])),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='code',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='name',
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='TravelPortalSearch.Country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='TravelPortalSearch.City'),
            preserve_default=False,
        ),
    ]
